version: '3.4'

services:
  idenmssqldb:
    container_name: eshop-store-identity
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Sample@123$"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  identity.api:
    container_name: eshop-services-identity
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - "ConnectionStrings__DefaultConnection=Data Source=idenmssqldb;User ID=sa;Initial Catalog=eShop-Identity;Password=Sample@123$;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False"
    depends_on:
      - idenmssqldb
    ports:
      - "8002:80"
      - "8003:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
